name: Shelly
on:
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck (strict mode)
        run: |
          find . -name "*.sh" -exec shellcheck --severity=warning {} \;
          if find . -name "*.sh" -exec shellcheck --format=gcc {} \; | grep -q "warning"; then
            echo "ShellCheck warnings found"
            exit 1
          fin: sudo apt-get install shellcheck

